using System.Text;
using LaunchForge.Models;
using LaunchForge.Models.Steps;

namespace LaunchForge.Services;

public static class ScriptGenerator
{
    // ── .bat generation ──────────────────────────────────────────────────────

    public static string GenerateBat(Sequence sequence)
    {
        var sb = new StringBuilder();

        sb.AppendLine("@echo off");
        sb.AppendLine("setlocal enabledelayedexpansion");
        sb.AppendLine($":: {sequence.Name}");
        sb.AppendLine($":: Generated by LaunchForge on {DateTime.Now:yyyy-MM-dd HH:mm}");
        sb.AppendLine();

        for (int i = 0; i < sequence.Steps.Count; i++)
        {
            var step = sequence.Steps[i];
            var comment = string.IsNullOrWhiteSpace(step.Label)
                ? StepTypeName(step)
                : $"{StepTypeName(step)}: {step.Label}";

            if (!step.IsEnabled)
            {
                sb.AppendLine($":: [DISABLED] {comment}");
                sb.AppendLine();
                continue;
            }

            sb.AppendLine($":: Step {i + 1}: {comment}");
            sb.AppendLine(ToBatLine(step));
            sb.AppendLine();
        }

        sb.AppendLine("echo All done.");
        return sb.ToString();
    }

    private static string ToBatLine(StepBase step) => step switch
    {
        LaunchAppStep s when s.WaitForExit =>
            $"start /wait \"\" \"{s.ExePath}\"{(string.IsNullOrEmpty(s.Arguments) ? "" : " " + s.Arguments)}",

        LaunchAppStep s =>
            $"start \"\" \"{s.ExePath}\"{(string.IsNullOrEmpty(s.Arguments) ? "" : " " + s.Arguments)}",

        LaunchSteamStep s =>
            $"start \"\" \"steam://rungameid/{s.AppId}\"",

        WaitStep s =>
            $"timeout /t {s.Seconds} /nobreak",

        KillProcessStep s =>
            $"taskkill /f /im \"{EnsureExe(s.ProcessName)}\"",

        WaitForProcessStartStep s when s.TimeoutSeconds > 0 =>
            "powershell -Command \"" +
            $"$proc = '{s.ProcessName}'; $timeout = {s.TimeoutSeconds}; $start = Get-Date; " +
            "while ($true) { if (Get-Process $proc -ErrorAction SilentlyContinue) { break }; " +
            "if (((Get-Date) - $start).TotalSeconds -ge $timeout) { Write-Warning ('Timed out waiting for ' + $proc); break }; " +
            "Start-Sleep -Milliseconds 500 }\"",

        WaitForProcessStartStep s =>
            "powershell -Command \"" +
            $"$proc = '{s.ProcessName}'; " +
            "while (-not (Get-Process $proc -ErrorAction SilentlyContinue)) { Start-Sleep -Milliseconds 500 }\"",

        WaitForProcessExitStep s when s.TimeoutSeconds > 0 =>
            "powershell -Command \"" +
            $"$proc = '{s.ProcessName}'; $timeout = {s.TimeoutSeconds}; $start = Get-Date; " +
            "while (Get-Process $proc -ErrorAction SilentlyContinue) { " +
            "if (((Get-Date) - $start).TotalSeconds -ge $timeout) { Write-Warning ('Timed out waiting for ' + $proc + ' to exit'); break }; " +
            "Start-Sleep -Milliseconds 500 }\"",

        WaitForProcessExitStep s =>
            "powershell -Command \"" +
            $"$proc = '{s.ProcessName}'; " +
            "while (Get-Process $proc -ErrorAction SilentlyContinue) { Start-Sleep -Milliseconds 500 }\"",

        RunPowerShellStep s when s.WaitForExit =>
            WriteTempPs1Bat(s),

        RunPowerShellStep s =>
            WriteTempPs1Bat(s, noWait: true),

        _ => $":: (unknown step type: {step.GetType().Name})"
    };

    private static string WriteTempPs1Bat(RunPowerShellStep s, bool noWait = false)
    {
        // Escape quotes in the script for embedding in batch echo
        var sb2 = new StringBuilder();
        sb2.AppendLine("setlocal");
        sb2.AppendLine($"set _tmpfile=%TEMP%\\lf_ps_%RANDOM%.ps1");
        foreach (var line in s.Script.Replace("\r\n", "\n").Split('\n'))
        {
            // Batch echo has issues with special chars; safer to use the file approach
            sb2.AppendLine($"echo {EscapeBatchEcho(line)}>> %_tmpfile%");
        }
        if (noWait)
            sb2.AppendLine("start /b powershell -ExecutionPolicy Bypass -File %_tmpfile%");
        else
            sb2.AppendLine("powershell -ExecutionPolicy Bypass -File %_tmpfile%");
        sb2.AppendLine("del %_tmpfile%");
        sb2.Append("endlocal");
        return sb2.ToString();
    }

    // ── .ps1 generation ──────────────────────────────────────────────────────

    public static string GeneratePs1(Sequence sequence)
    {
        var sb = new StringBuilder();

        sb.AppendLine("#Requires -Version 5");
        sb.AppendLine("Set-StrictMode -Version Latest");
        sb.AppendLine($"# {sequence.Name}");
        sb.AppendLine($"# Generated by LaunchForge on {DateTime.Now:yyyy-MM-dd HH:mm}");
        sb.AppendLine();

        for (int i = 0; i < sequence.Steps.Count; i++)
        {
            var step = sequence.Steps[i];
            var comment = string.IsNullOrWhiteSpace(step.Label)
                ? StepTypeName(step)
                : $"{StepTypeName(step)}: {step.Label}";

            if (!step.IsEnabled)
            {
                sb.AppendLine($"# [DISABLED] {comment}");
                sb.AppendLine();
                continue;
            }

            sb.AppendLine($"# Step {i + 1}: {comment}");
            sb.AppendLine(ToPs1Block(step));
            sb.AppendLine();
        }

        sb.AppendLine("Write-Host 'All done.'");
        return sb.ToString();
    }

    private static string ToPs1Block(StepBase step) => step switch
    {
        LaunchAppStep s when s.WaitForExit =>
            $"Start-Process -FilePath '{EscapePs(s.ExePath)}'" +
            (string.IsNullOrEmpty(s.Arguments) ? "" : $" -ArgumentList '{EscapePs(s.Arguments)}'") +
            " -Wait",

        LaunchAppStep s =>
            $"Start-Process -FilePath '{EscapePs(s.ExePath)}'" +
            (string.IsNullOrEmpty(s.Arguments) ? "" : $" -ArgumentList '{EscapePs(s.Arguments)}'"),

        LaunchSteamStep s =>
            $"Start-Process 'steam://rungameid/{s.AppId}'",

        WaitStep s =>
            $"Start-Sleep -Seconds {s.Seconds}",

        KillProcessStep s =>
            $"Stop-Process -Name '{EscapePs(s.ProcessName)}' -Force -ErrorAction SilentlyContinue",

        WaitForProcessStartStep s when s.TimeoutSeconds > 0 => string.Join(Environment.NewLine,
            $"$_proc = '{EscapePs(s.ProcessName)}'; $_timeout = {s.TimeoutSeconds}; $_start = Get-Date",
            "while ($true) {",
            "    if (Get-Process $_proc -ErrorAction SilentlyContinue) { break }",
            $"    if (((Get-Date) - $_start).TotalSeconds -ge $_timeout) {{ Write-Warning \"Timed out waiting for $_proc to start\"; break }}",
            "    Start-Sleep -Milliseconds 500",
            "}"),

        WaitForProcessStartStep s => string.Join(Environment.NewLine,
            $"$_proc = '{EscapePs(s.ProcessName)}'",
            "while (-not (Get-Process $_proc -ErrorAction SilentlyContinue)) {",
            "    Start-Sleep -Milliseconds 500",
            "}"),

        WaitForProcessExitStep s when s.TimeoutSeconds > 0 => string.Join(Environment.NewLine,
            $"$_proc = '{EscapePs(s.ProcessName)}'; $_timeout = {s.TimeoutSeconds}; $_start = Get-Date",
            "while (Get-Process $_proc -ErrorAction SilentlyContinue) {",
            $"    if (((Get-Date) - $_start).TotalSeconds -ge $_timeout) {{ Write-Warning \"Timed out waiting for $_proc to exit\"; break }}",
            "    Start-Sleep -Milliseconds 500",
            "}"),

        WaitForProcessExitStep s => string.Join(Environment.NewLine,
            $"$_proc = '{EscapePs(s.ProcessName)}'",
            "while (Get-Process $_proc -ErrorAction SilentlyContinue) {",
            "    Start-Sleep -Milliseconds 500",
            "}"),

        RunPowerShellStep s when s.WaitForExit => string.Join(Environment.NewLine,
            "& {",
            s.Script,
            "}"),

        RunPowerShellStep s => string.Join(Environment.NewLine,
            "Start-Job -ScriptBlock {",
            s.Script,
            "} | Out-Null"),

        _ => $"# (unknown step type: {step.GetType().Name})"
    };

    // ── Helpers ───────────────────────────────────────────────────────────────

    private static string StepTypeName(StepBase step) => step switch
    {
        LaunchAppStep           => "Launch App",
        LaunchSteamStep         => "Launch Steam",
        WaitStep                => "Wait",
        KillProcessStep         => "Kill Process",
        WaitForProcessStartStep => "Wait for Process Start",
        WaitForProcessExitStep  => "Wait for Process Exit",
        RunPowerShellStep       => "Run PowerShell",
        _                       => step.GetType().Name,
    };

    private static string EnsureExe(string name) =>
        name.EndsWith(".exe", StringComparison.OrdinalIgnoreCase) ? name : name + ".exe";

    private static string EscapePs(string s) => s.Replace("'", "''");

    // Escapes a line for use in batch ECHO; strips or replaces characters that confuse the parser
    private static string EscapeBatchEcho(string line)
    {
        // A blank line would just emit "ECHO is on/off", so use a dot trick
        if (string.IsNullOrEmpty(line)) return ".";
        return line
            .Replace("%", "%%")
            .Replace("^", "^^")
            .Replace("&", "^&")
            .Replace("<", "^<")
            .Replace(">", "^>")
            .Replace("|", "^|");
    }
}
